# Generated by Django 5.2 on 2025-04-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_customer_delete_user'),
        ('registration', '0003_alter_customer_managers'),
    ]

    operations = [
    ]
